http:
  host: [127, 0, 0, 1]
  port: 8080
i18n:
  path: "i18n"
  fallback: en-US
database:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres
  database: postgres
  require_ssl: false
id:
  secret: ""
hasher:
  secret: ""
  memory_size: 16
  iterations: 1
  parallelism_factor: 1
  output_length: 32
jwt:
  ttl: 900
  secret: ""
templates:
  path: "templates/**/*.html"
