http:
  host: [0, 0, 0, 0]
  port: 8080
templates:
  path: "templates/**/*.html"
database:
  host: ""
  port: 0
  user: ""
  password: ""
  database: ""
  require_ssl: true
hasher:
  secret: ""
  memory_size: 4096
  iterations: 3
  parallelism_factor: 1
  output_length: 32
