http:
  host: [0, 0, 0, 0]
  port: 8080
i18n:
  path: "i18n"
  fallback: en-US
database:
  host: ""
  port: 0
  user: ""
  password: ""
  database: ""
  require_ssl: true
signature:
  secret: ""
id:
  secret: ""
hasher:
  secret: ""
  memory_size: 4096
  iterations: 3
  parallelism_factor: 1
  output_length: 32
jwt:
  ttl: 900
  secret: ""
templates:
  path: "templates/**/*.html"
